-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 13:51:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cocktails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cocktails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cocktails` (
  `cocktail_id` INT NOT NULL AUTO_INCREMENT,
  `cocktail_name` VARCHAR(45) NULL,
  PRIMARY KEY (`cocktail_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingedients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ingedients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ingedients` (
  `ingedient_id` INT NOT NULL AUTO_INCREMENT,
  `cocktail_id` INT NULL,
  `ingredient_name` VARCHAR(45) NULL,
  `taste_profile` VARCHAR(45) NULL,
  PRIMARY KEY (`ingedient_id`),
  INDEX `cocktail_id_idx` (`cocktail_id` ASC) VISIBLE,
  CONSTRAINT `cocktail_id`
    FOREIGN KEY (`cocktail_id`)
    REFERENCES `mydb`.`Cocktails` (`cocktail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Measurements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Measurements` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Measurements` (
  `measurement_id` INT NOT NULL AUTO_INCREMENT,
  `cocktail_id` INT NULL,
  `ingredient_id` INT NULL,
  `quanitity` INT NULL,
  `measurement_name` VARCHAR(45) NULL,
  `num_ounces` FLOAT NULL,
  PRIMARY KEY (`measurement_id`),
  INDEX `cocktail_id_idx` (`cocktail_id` ASC) VISIBLE,
  INDEX `ingredient_id_idx` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `cocktail_id`
    FOREIGN KEY (`cocktail_id`)
    REFERENCES `mydb`.`Cocktails` (`cocktail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ingredient_id`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `mydb`.`Ingedients` (`ingedient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tools` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tools` (
  `tools_id` INT NOT NULL AUTO_INCREMENT,
  `cocktail_id` INT NULL,
  `tool_name` VARCHAR(45) NULL,
  PRIMARY KEY (`tools_id`),
  INDEX `cocktail_id_idx` (`cocktail_id` ASC) VISIBLE,
  CONSTRAINT `cocktail_id`
    FOREIGN KEY (`cocktail_id`)
    REFERENCES `mydb`.`Cocktails` (`cocktail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipe_steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recipe_steps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recipe_steps` (
  `recipe_steps_id` INT NOT NULL,
  `cocktail_id` INT NULL,
  `ingredients_id` INT NULL,
  `measurement_id` INT NULL,
  `tool_id` INT NULL,
  `step_number` INT NULL,
  `step_description` VARCHAR(300) NULL,
  PRIMARY KEY (`recipe_steps_id`),
  INDEX `cocktail_id_idx` (`cocktail_id` ASC) VISIBLE,
  INDEX `measurement_id_idx` (`measurement_id` ASC) VISIBLE,
  INDEX `ingredient_id_idx` (`ingredients_id` ASC) VISIBLE,
  INDEX `tool_id_idx` (`tool_id` ASC) VISIBLE,
  CONSTRAINT `cocktail_id`
    FOREIGN KEY (`cocktail_id`)
    REFERENCES `mydb`.`Cocktails` (`cocktail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `measurement_id`
    FOREIGN KEY (`measurement_id`)
    REFERENCES `mydb`.`Measurements` (`measurement_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ingredient_id`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `mydb`.`Ingedients` (`ingedient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tool_id`
    FOREIGN KEY (`tool_id`)
    REFERENCES `mydb`.`Tools` (`tools_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
