# Generated by Django 4.0 on 2021-12-14 19:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktails',
            fields=[
                ('cocktail_id', models.AutoField(default=uuid.uuid4, help_text='Unique ID for this particular cocktail', primary_key=True, serialize=False)),
                ('cocktail_name', models.CharField(help_text='What is the name of this cocktail', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingedients',
            fields=[
                ('ingredient_id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('ingredient_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('measurement_id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('measurement_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('num_ounces', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('tool_id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('recipe_steps_id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('step_description', models.CharField(blank=True, max_length=500, null=True)),
                ('cocktail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cocktails')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ingedients')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.measurements')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.tools')),
            ],
        ),
    ]
