# Generated by Django 4.0 on 2021-12-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ingredients_alter_cocktails_cocktail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktails',
            name='alcoholic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cocktails',
            name='glass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
