# Generated by Django 4.0 on 2022-01-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0004_remove_cocktails_glass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cocktails',
            old_name='cocktail_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cocktails',
            old_name='cocktail_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredient_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='measurements',
            old_name='measurement_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='recipesteps',
            old_name='recipe_steps_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredient_name',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredient_type',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='num_ounces',
        ),
        migrations.AddField(
            model_name='cocktails',
            name='training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='alcoholic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='type',
            field=models.CharField(choices=[('alcohol', 'Alcohol'), ('mixer', 'Mixer'), ('modifier', 'Modifier')], default='alcohol', max_length=10),
        ),
        migrations.AddField(
            model_name='measurements',
            name='amount_ounces',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurements',
            name='original_measurement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.measurements')),
                ('chromosome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.chromosome')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ingredients')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
