# Generated by Django 4.0 on 2022-01-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_chromosome_rename_cocktail_id_cocktails_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chromosome',
            new_name='ChromosomeDB',
        ),
        migrations.RenameField(
            model_name='gene',
            old_name='chromosome',
            new_name='chromosomeDB',
        ),
        migrations.AlterField(
            model_name='measurements',
            name='original_measurement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
